CREATE TABLE workouts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES amrap_users(id),
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
  workout_length INTEGER NOT NULL, 
  CHECK (workout_length BETWEEN 5 and 60)
);