CREATE TABLE workouts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES amrap_users(id),
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
  workout_length INTEGER NOT NULL, 
  CHECK (workout_length BETWEEN 5 and 60),
  movement_1 INTEGER REFERENCES movements(id) ON DELETE SET NULL,
  movement_2 INTEGER REFERENCES movements(id) ON DELETE SET NULL,
  movement_3 INTEGER REFERENCES movements(id) ON DELETE SET NULL,
  movement_4 INTEGER REFERENCES movements(id) ON DELETE SET NULL,
  movement_5 INTEGER REFERENCES movements(id) ON DELETE SET NULL
);